export const mockProducts = [
  {
    _id: 'prod_1',
    name: 'Sony WH-1000XM5 Wireless Headphones',
    price: 29990,
    discount: 15,
    images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80'],
    description: 'Industry-leading noise cancelling with two processors and 8 microphones. Magnificent sound quality, engineered to perfection.',
    stock: 18,
    category: 'Electronics',
    rating: 4.8,
    isFeatured: true,
    supplier: { businessName: 'Sony Store' },
  },
  {
    _id: 'prod_2',
    name: 'Apple Watch Series 9 GPS 45mm',
    price: 44900,
    discount: 10,
    images: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80'],
    description: 'Powerful S9 SiP chip, double tap gesture, brighter display, faster on-device Siri, and health tracking.',
    stock: 25,
    category: 'Wearables',
    rating: 4.9,
    isFeatured: true,
    supplier: { businessName: 'Apple Official' },
  },
  {
    _id: 'prod_3',
    name: 'Logitech MX Master 3S Ergonomic Mouse',
    price: 9995,
    discount: 12,
    images: ['https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=800&q=80'],
    description: 'Quiet clicks and 8K DPI any-surface tracking. Ergonomic design crafted for comfort and precise productivity.',
    stock: 40,
    category: 'Accessories',
    rating: 4.7,
    isFeatured: true,
    supplier: { businessName: 'Logitech Hub' },
  },
  {
    _id: 'prod_4',
    name: 'Dell XPS 15 OLED Laptop',
    price: 185000,
    discount: 8,
    images: ['https://images.unsplash.com/photo-1593642632823-8f785ba67e45?auto=format&fit=crop&w=800&q=80'],
    description: '15.6-inch OLED 3.5K touch display, Intel i9 processor, 32GB RAM, 1TB SSD, NVIDIA GeForce RTX 4060.',
    stock: 10,
    category: 'Computers',
    rating: 4.6,
    isFeatured: false,
    supplier: { businessName: 'Dell Enterprise' },
  },
  {
    _id: 'prod_5',
    name: 'Keychron K2 Mechanical Keyboard',
    price: 7499,
    discount: 5,
    images: ['https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80'],
    description: '75% Layout Wireless Mechanical Keyboard with RGB backlighting for Mac and Windows.',
    stock: 30,
    category: 'Accessories',
    rating: 4.5,
    isFeatured: false,
    supplier: { businessName: 'Keychron India' },
  },
  {
    _id: 'prod_6',
    name: 'Samsung 32" Odyssey Curved Gaming Monitor',
    price: 49990,
    discount: 20,
    images: ['https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=80'],
    description: '1000R Curved Screen, 240Hz Refresh Rate, 1ms Response Time, QLED technology for vivid visuals.',
    stock: 12,
    category: 'Monitors',
    rating: 4.7,
    isFeatured: true,
    supplier: { businessName: 'Samsung Electronics' },
  },
  {
    _id: 'prod_7',
    name: 'Nike Air Max 270 Sneakers',
    price: 12995,
    discount: 15,
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
    description: 'Boasts Nike\'s biggest heel Air unit yet for a super-soft ride that feels as impossible as it looks.',
    stock: 50,
    category: 'Footwear',
    rating: 4.8,
    isFeatured: true,
    supplier: { businessName: 'Nike Official Store' },
  },
  {
    _id: 'prod_8',
    name: 'Canon EOS R6 Mark II Mirrorless Camera',
    price: 215000,
    discount: 10,
    images: ['https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=800&q=80'],
    description: '24.2 MP full-frame CMOS sensor, 40 fps continuous shooting, 4K 60p video recording.',
    stock: 8,
    category: 'Electronics',
    rating: 4.9,
    isFeatured: false,
    supplier: { businessName: 'Canon Pro Center' },
  }
];

export const mockCategories = [
  { _id: 'cat_1', name: 'Electronics', icon: 'Headphones' },
  { _id: 'cat_2', name: 'Wearables', icon: 'Watch' },
  { _id: 'cat_3', name: 'Accessories', icon: 'Mouse' },
  { _id: 'cat_4', name: 'Computers', icon: 'Laptop' },
  { _id: 'cat_5', name: 'Monitors', icon: 'Tv' },
  { _id: 'cat_6', name: 'Footwear', icon: 'ShoppingBag' }
];
